### ISSUE TITLE
Compiling Error

### ISSUE THREAD

**Issue by Eastnova** [tikzit/tikzit#39] opened 2018-10-27 15:03 UTC
I followed the building instruction under Windows 10 environment, but the following message appears.
......
tikzparser.parser.cpp
..\tikzit-master\src\data\tikzparser.y(65): fatal error C1083: Cannot open include file: 'tikzlexer.h': No such file or directory
......
Can anyone please tell me how to solve this? win_flex and win_bison have been installed correctly.
Thanks in advance.

**Comment by akissinger** [comment] 2018-10-27 15:50
I've encountered this issue occasionally in the past, but (seemingly) somewhat randomly. Are you building with Qt Creator, Visual Studio, or nmake? Running nmake from the command line seems to the be most reliable on Windows. I'm using the one included in VS2017 community edition.

tikzlexer.h used to be included in the repo, but I recently removed it, since it should be generated from running flex. This might have confused your build environment if it is doing some caching. I know Qt Creator and qmake are a bit sensitive to this.

**Comment by Eastnova** [comment] 2018-10-28 03:46
I followed the building instructions:

choco install winflexbison
C:\Qt\5.11.1\msvc2015_64\bin\qtenv2.bat
call "C:\ProgramFiles (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x64
cd C:\path\to\tikzit
qmake
nmake

The only difference is that Qt 5.11.2 is used.

**Comment by akissinger** [comment] 2018-10-29 06:57
Do you get the header file when you run flex manually? Here's the command that should be getting called:

    win_flex.exe --header-file -o src/data/tikzlexer.lexer.cpp src/data/tikzlexer.l

**Comment by akissinger** [comment] 2018-10-30 16:14
Glad it worked.

I'll close this for now, but I think there might be some problem with the way `tikzit.pro` handles dependencies for flex/bison. I'll try to reproduce.

**Closed by akissinger** 2018-10-30 16:14 UTC
